# Generated by Django 2.2.5 on 2019-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.TextField()),
                ('age', models.IntegerField(null=True)),
                ('job_postition', models.TextField(max_length=225, null=True)),
            ],
        ),
    ]
