# Generated by Django 2.2.5 on 2019-09-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='job_postition',
            new_name='job_position',
        ),
    ]
